name: CI/CD

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Build application
      run: docker build -t cargo-solutions .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Executing test
      run: docker-compose run --rm test

    - name: Stop services
      run: docker-compose down -v
    
